SHOW DATABASES;
CREATE DATABASE IF NOT EXISTS WEB_APP_DEMO;
USE WEB_APP_DEMO;
STATUS;

SOURCE ./Modals/User.sql;
SOURCE ./Modals/Contact_info.sql;
SOURCE ./Modals/Post.sql;
SOURCE ./Modals/Events.sql;
SOURCE ./Modals/Events_User.sql;





/*
    THIS IS A WEB APPLICATION DEMO IN TERM OF DATABASE ACESS AND SCHEMA DESIGN

    ONE TO ONE RELATIONSHIPS
        -- EVERY USER CAN HAVE ONLY ONE CONTACT INFO
        -- EACH CONTACT INFO BELONGS TO ONE USER;

    

    ONE TO MANY RELATIONSHIPS
        -- EVERY USER CAN BE THE AUTHOR OF MANY POSTS;
        -- EACH POST BELONGS TO ONE USER/AUTHOR;


    MANY TO MANY RELATIONSHIP
        -- EVERY USER CAN HOST MULTIPLE EVENTS;
        -- EACH EVENT CAN HAVE MULTIPLE USERS PARTICIPATING TO IT;

    

    MEANING-FULL JOIN POSSIBILITIES;

        -- USER && CONTACT INFO
        -- USER && POST
        -- POST && CONTACT INFO


*/











